version: "3.8"

services:
  database:
    image: mariadb
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: toor
      # MARIADB_RANDOM_ROOT_PASSWORD: 1
      # MARIADB_USER: $MARIADB_USER
      # MARIADB_PASSWORD: $MARIADB_PASSWORD
      # MARIADB_DATABASE: $MARIADB_DATABASE

  backend:
    # image: xedom/codeduel-be
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    environment:
      MARIADB_HOST: database
      MARIADB_PORT: 3306
      MARIADB_USER: root
      MARIADB_PASSWORD: toor
      MARIADB_DATABASE: codeduel
    depends_on:
      - database
  
  frontend:
    image: xedom/codeduel-fe
    container_name: frontend
    restart: always
    ports:
      - 8080:80
    environment:
      BACKEND_URL: http://backend:5000
    depends_on:
      - backend
